fallback:
  token:
################ Additional configurations for USSD #########################
ussd:
  logging:
    verbose: true
  session:
    repository: memory
  menu:
    goBackOption: 0
    nextOption: "00"
  baseCode:
  service:
    charge:

eventId:
  transaction: NIP_PAYOUT
  airtimeAndDataQuickTeller: QUICKTELLER
  airtimeAndDataBaxi: BAXI
  airtimeAndDataItex: ITEX

session:
  continue: "CON "
  end: "END "

user:
  password:
  emailOrPhone:

afrikasTalking:
  callback:
    accepted-origins:


