server:
  port: ${USSD_SERVICE_SERVER_PORT:9999}
  error:
    include-message: always
  servlet:
    context-path: /ussd-service
spring:
  main:
    allow-bean-definition-overriding: true
  jackson:
    serialization:
      fail-on-empty-beans: false
  application:
    name: ussd-service
  datasource:
    url: ${USSD_SVC_DATASOURCE_URL:jdbc:postgresql://localhost:5432/WayaPayChatTemporalWalletDB?useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC}
    username: ${USSD_SVC_DATASOURCE_USERNAME:postgres}
    password: ${USSD_SVC_DATASOURCE_PASSWORD:password}
    initialization-mode: always
    driver-class-name: org.postgresql.Driver
    continue-on-error: true
  zipkin:
    enabled: true
    base-url: ${ZIKIN_URL:https://zipkin.waya-pay.com}
  sleuth:
    sampler:
      percentage: 1.0
    web:
      skipPattern: (^cleanup.*|.+favicon.*)
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        storage_engine: innodb
        jdbc:
          time_zone: UTC
    open-in-view: false #this config disables database queries which  may be performed during view rendering

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:https://services.staging.wayapay.ng}
    service-url:
      default-zone:${EUREKA_SERVER_URL:https://services.staging.wayapay.ng}
  instance:
    preferIpAddress: true
jwt:
  secret: ${USSD_JWT_SECRET:BvPHGM8C0ia4uOuxxqPD5DTbWC9F9TWvPStp3pb7ARo0oK2mJ3pd3YG4lxA9i8bj6OTbadwezxgeEByY}
  expiration: ${USSD_JWT_EXPIRATION:86400}

kafka:
  bootstrapServers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
  groupId: ${KAFKA_GROUP_ID:waya}
  consumer:
    group-id: waya
    auto-offset-reset: newest

service-key:
  auth_get_user_key: ${AUTH_GET_USER_WALLET_KEY:WALMIFOS}

app:
  config:
    wallet:
      base-url: ${CONFIG_BASEURL_MWALLET:https://services.staging.wayapay.ng/temporal-service/api/v1/wallet}
    auth-service:
      base-url: ${AUTHENTICATION_SERVICE_BASEURL:https://services.staging.wayabank.ng/auth-service/api/v1}
    notification:
      base-url: ${CONFIG_BASEURL_NOTIFICATION:https://services.staging.wayapay.ng/notification-service/api/v1}
    kyc-service:
      base-url: ${CONFIG_BASEURL_KYC:https://services.staging.wayapay.ng/kyc-service}
    coralpay:
      base-url: ${CORALPAY_BASE_URL:https://testdev.coralpay.com/cgateproxy/api}
      username: ${CORALPAY_USERNAME:wayapay}
      password: ${CORALPAY_PASSWORD:2103023822@003#0}
      merchant-id: ${CORALPAY_MERCHANT_ID:1057WPY10000001}
      terminal-id: ${CORALPAY_TERMINAL_ID:1057WPY1}
    payment-gateway-service:
      base-url: ${CORALPAY_BASE_URL:https://services.staging.wayapay.ng/payment-gateway/api/v1}
    waya-merchant:
      base-url: https://services.staging.wayapay.ng/identity-manager-service/api/v1
      api-key: 2ccd7030-fbb8-411f-a6bc-1e762604458b
    waya:
      username: ${DEAMON_USERNAME:tbaadm@wayapaychat.com}
      password: ${DEAMON_PASSWORD:fintemp@#123}

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
      type:
        descriptor:
          sql:
            BasicBinder: TRACE

###################################### Waya Bank Configuration ######################
wayabank:
  apiPaths:
    appUserAuth: https://services.staging.wayabank.ng/auth-service/api/v1/auth/login
    authCustomer: https://services.staging.wayabank.ng/auth-service/api/v1/profile/phone
    customerDetailsByPhone: https://services.staging.wayabank.ng/auth-service/api/v1/profile/phone
    customerAccountsBase: https://services.staging.wayabank.ng/temporal-service/api/v1/wallet/accounts
    accountBalanceCheck: https://services.staging.wayabank.ng/temporal-service/api/v1/wallet/account
    createNewCustomer: https://services.staging.wayabank.ng/auth-service/api/v1/auth/create
    verifyOtp: https://services.staging.wayabank.ng/auth-service/api/v1/auth/verify-phone
    verifyEmail: https://services.staging.wayabank.ng/auth-service/api/v1/auth/verify-email
    billerCategoryBase: https://services.staging.wayabank.ng/billspayment-service/api/v1/category
    billerPayment: https://services.staging.wayabank.ng/billspayment-service/api/v1/biller/pay
    billPaymentPayBill: https://services.staging.wayabank.ng/billspayment-service/api/v1/category/cabletv
    getBanks: https://services.staging.wayabank.ng/card-service/bankAccount/getBanks/WD
    beneficiaryNameEnquiry: https://services.staging.wayabank.ng/card-service/bankAccount/resolveAccountNumber/WD
    fundsTransfer: https://services.staging.wayabank.ng/withdrawal-service/withdrawal/fund
    fundsTransferInternal: https://services.staging.wayabank.ng/contact-service/contact/account/service/send/money/userWallet/to/wallet/{senderId}/{senderAcctNo}/{beneficialAcctNo}?amount={amount}
    nameEnquiryInternal: https://services.staging.wayabank.ng/temporal-serviceapi/v1/wallet/info/{accountNumber}
    chargeCustomer: https://services.staging.wayabank.ng/temporal-service/api/v1/wallet/event/charge/payment
    validateBill: https://services.staging.wayabank.ng/billspayment-service/api/v1/biller/validate
    airtimeBiller: https://services.staging.wayabank.ng/billspayment-service/api/v1/category/airtime
    dataBiller: https://services.staging.wayabank.ng/billspayment-service/api/v1/category/databundle
    userTransactionFee: https://services.staging.wayabank.ng/temporal-service/api/v1/wallet/transaction/get-user-transaction-fee/{accountNo}/{amount}/{entityId}
    billPaymentAggregator: https://services.staging.wayabank.ng/billspayment-service/api/v1/config/aggregator

fallback:
  token: serial eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjpbeyJjcmVhdGVkQXQiOiIwNy0xMS0yMDIyIDEwOjM4OjI3IiwidXBkYXRlZEF0IjoiMDctMTEtMjAyMiAxMDozODoyNyIsImNyZWF0ZWRCeSI6Ik1HUiIsIm1vZGlmaWVkQnkiOiJNR1IiLCJpZCI6MTAsIm5hbWUiOiJST0xFX1VTRVJfT1dORVIiLCJkZXNjcmlwdGlvbiI6IkNVU1RPTUVSIiwiZGVmYXVsdCI6dHJ1ZSwiYWRtaW5Sb2xlIjpmYWxzZX1dLCJpZCI6MjE1OCwic3ViIjoiaW50ZWdyYXRpb250ZXN0YWNjb3VudEB5b3BtYWlsLmNvbSIsImlhdCI6MTY4MDI2MzY1MCwiZXhwIjoxNzExODIxMjUwfQ.lXmK_01ACUaw0pMpwYAd45fiH09wanhwrZwhqh8CNhH41QoRb3qUo4Vt97lSVszH3zI3mhUXzQ24bNLVVfY_7w

################ Additional configurations for USSD #########################
ussd:
  logging:
    verbose: true
  session:
    repository: memory
  menu:
    goBackOption: 0
    nextOption: "00"
  baseCode: "*347*006#"
  service:
    charge: "5"

eventId:
  transaction: NIP_PAYOUT
  airtimeAndDataQuickTeller: QUICKTELLER
  airtimeAndDataBaxi: BAXI
  airtimeAndDataItex: ITEX

session:
  continue: "CON "
  end: "END "

user:
  password: Password@123
  emailOrPhone: edceebee@gmail.com

afrikasTalking:
  callback:
    accepted-origins:


